# from an Ubuntu 24.04 LTS image
FROM ubuntu:24.04

# Commands to run
RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y curl python3-full openssh-server iputils-ping mysql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Command to install pip by the 'curl' command, and then install AWS with pip
# You'll need to activate the VENV everytime that you use this Docker
# Remember, for Linux: source /path/to/VENV/bin/activate
# For windows: cd /path/to/VENV
#                 /Scripts/activate
RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3 -m venv AWS_via_PIP && \
    . AWS_via_PIP/bin/activate && \
    python3 get-pip.py && \
    pip install awscli --upgrade

# Create the /run/sshd directory
RUN mkdir -p /run/sshd

# Create a user, assign a password to that user
# And create a home folder for itself. (and the .ssh file)
# And give permissions to .ssh file (700)
RUN if ! id -u remote_user > /dev/null 2>&1; then \
        useradd -m -d /home/remote_user remote_user && \
        echo "remote_user:030414" | chpasswd && \
        mkdir -p /home/remote_user/.ssh && \
        chmod 700 /home/remote_user/.ssh; \
    fi

# Copy command to copy the ssh key previously generated
COPY remote-key.pub /home/remote_user/.ssh/authorized_keys

# Give permissions to the folder '.ssh'
RUN chown remote_user:remote_user -R /home/remote_user/.ssh && \
    chmod 600 /home/remote_user/.ssh/authorized_keys

# Path to openssh-server
RUN ssh-keygen -A

# Expose SSH port
EXPOSE 22

# Which command are going to run in order in this Dockerfile
CMD ["/usr/sbin/sshd", "-D"]

