# Use of "version #" is now deprecated (you can use it, but will throw a warning)
# version: '3.8'

services:
  jenkins:
    container_name: jenkinsOnDocker
    image: jenkins/jenkins:2.472-jdk17
    command: bash -c "apt-get update && apt-get install -y iputils-ping && /usr/bin/tini -- /usr/local/bin/jenkins.sh"
    ports:
      - "8080:8080"
      - "50000:50000"
    privileged: true
    user: root
    environment:
      - TZ=America/Bogota
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-docker-certs:/certs/client:ro
        #network_mode: host
    networks:
      - trainingNetwork
# New Container to create and connect via SSH
  remote_host:
    container_name: remote-host
    image: debian:stable-slim
    build:
      context: ../unit2-jenkins-and-docker
    networks:
      - trainingNetwork
networks:
  trainingNetwork:
    external: true

volumes:
  jenkins-data:
    external: true
  jenkins-docker-certs:
